export const cards = [
  { id: 1, pol: 'ja', jap: 'watashi', kana: 'わたし' },
  { id: 2, pol: 'ty', jap: 'anata', kana: 'あなた' },
  { id: 3, pol: 'on', jap: 'kare', kana: 'かれ' },
  { id: 4, pol: 'ona', jap: 'kanojo', kana: 'かのじょ' },
  { id: 5, pol: 'nudny', jap: 'tsumaranai', kana: 'つまらない' },
  { id: 6, pol: 'biologia', jap: 'seibutsugaku', kana: 'せいぶつがく' },
  { id: 7, pol: 'fizyka', jap: 'butsurigaku', kana: 'ぶつりがく' },
  { id: 8, pol: 'rozumieć', jap: 'wakaru', kana: 'わかる' },
  { id: 9, pol: 'robić', jap: 'suru', kana: 'する' },
  { id: 10, pol: 'wyjmować', jap: 'dasu', kana: 'だす' },
  { id: 11, pol: 'odpoczywać', jap: 'yasumu', kana: 'やすむ' },
  { id: 12, pol: 'spać', jap: 'neru', kana: 'ねる' },
  { id: 13, pol: 'wstawać, budzić się', jap: 'okiru', kana: 'おきる' },
  { id: 14, pol: 'przychodzić, przyjeżdżać', jap: 'kuru', kana: 'くる' },
  { id: 15, pol: 'dziewczynka', jap: 'onna-no ko', kana: 'おんなのこ' },
  { id: 16, pol: 'chłopiec', jap: 'otoko-no ko', kana: 'おとこのこ' },
  { id: 17, pol: 'bliski', jap: 'chikai', kana: 'ちかい' },
  { id: 18, pol: 'mąż (mój)', jap: 'shujin, otto', kana: 'しゅじん, おっと' },
  { id: 19, pol: 'prezent', jap: 'purezento', kana: 'プレゼント' },
  { id: 20, pol: 'czekoladka', jap: 'chokoreeto', kana: 'チョコレート' },
  { id: 21, pol: 'książka', jap: 'hon', kana: 'ほん' },
  { id: 22, pol: 'samochód', jap: 'kuruma, jidousha', kana: 'くるま, じどうしゃ' },
  { id: 23, pol: 'rower', jap: 'jitensha', kana: 'じてんしゃ' },
  { id: 24, pol: 'prawda', jap: 'hontou', kana: 'ほんとう' },
  { id: 25, pol: 'album', jap: 'arubamu', kana: 'アルバム' },
  { id: 26, pol: 'pałeczki', jap: 'hashi', kana: 'はし' },
  { id: 27, pol: 'aparat fotograficzny', jap: 'kamera', kana: 'カメラ' },
  { id: 28, pol: '10', jap: 'juu', kana: 'じゅう' },
  { id: 29, pol: '100', jap: 'hyaku', kana: 'ひゃく' },
  { id: 30, pol: '1000', jap: 'sen', kana: 'せん' },
  { id: 31, pol: 'dziecko (moje)', jap: 'kodomo', kana: 'こども' },
  { id: 32, pol: 'stary', jap: 'furui', kana: 'ふるい' },
  { id: 33, pol: 'nie, to nieprawda', jap: 'iie, chigaimasu', kana: 'いいえ, ちがいます' },
  { id: 34, pol: 'specjalista', jap: 'senmonka', kana: 'せんもんか' },
  { id: 35, pol: 'uczeń', jap: 'seito', kana: 'せいと' },
  { id: 36, pol: 'uczyć', jap: 'oshiete imasu', kana: 'おしえています' },
  { id: 37, pol: 'poczta', jap: 'yuubinkyouku', kana: 'ゆうびんきょく' },
  { id: 38, pol: 'dobry', jap: 'ii', kana: 'いい' },
  { id: 39, pol: 'szkoła', jap: 'gakkou', kana: 'がっこう' },
  { id: 40, pol: 'adres (mój)', jap: 'juusho', kana: 'じゅうしょ' },
  { id: 41, pol: 'adres (pański)', jap: 'gojuusho', kana: 'ごじゅうしょ' },
  { id: 42, pol: 'ciemny', jap: 'kurai', kana: 'くらい' },
  { id: 43, pol: 'głęboki', jap: 'fukai', kana: 'ふかい' },
  { id: 44, pol: 'zdrowy', jap: 'genki-na', kana: 'げんきな' },
  { id: 45, pol: 'cichy', jap: 'shizuka-na', kana: 'しずかな' },
  { id: 46, pol: 'współczesny', jap: 'kindaiteki-na', kana: 'きんだいてきな' },
  { id: 47, pol: 'miły', jap: 'shinsetsu-na', kana: 'しんせつな' },
  { id: 48, pol: 'żona (moja)', jap: 'tsuma, kanai', kana: 'つま, かない' },
  { id: 49, pol: 'zapracowany', jap: 'isogashii', kana: 'いそがしい' },
  { id: 50, pol: 'zebranie, narada', jap: 'kaigi', kana: 'かいぎ' },
  { id: 51, pol: 'piękny', jap: 'utsukushii', kana: 'うつくしい' },
  { id: 52, pol: 'miasto, blok, ulica, droga, sąsiedztwo', jap: 'machi', kana: 'まち' },
  { id: 53, pol: 'żona (pańska)', jap: 'okusan', kana: 'おくさん' },
  { id: 54, pol: 'szpital', jap: 'byouin', kana: 'びょういん' },
  { id: 55, pol: 'nowoczesny', jap: 'modan-na', kana: 'モダンな' },
  { id: 56, pol: 'pożyteczny', jap: 'benri-na', kana: 'べんりな' },
  { id: 57, pol: 'gruby', jap: 'futoi', kana: 'ふとい' },
  { id: 58, pol: 'długi', jap: 'nagai', kana: 'ながい' },
  { id: 59, pol: 'trudny', jap: 'muzukashii', kana: 'むずかしい' },
  { id: 60, pol: 'niemiły', jap: 'fushinsetsu-na', kana: 'ふしんせつな' },
  { id: 61, pol: 'wysoki, drogi', jap: 'takai', kana: 'たかい' },
  { id: 62, pol: 'straszny', jap: 'taihen-na', kana: 'たいへんな' },
  { id: 63, pol: 'czarny', jap: 'kuroi', kana: 'くろい' },
  { id: 64, pol: 'interesujący', jap: 'omoshiroi', kana: 'おもしろい' },
  { id: 65, pol: 'nieprzydatny', jap: 'fuben-na', kana: 'ふべんな' },
  { id: 66, pol: 'krótki', jap: 'mijikai', kana: 'みじかい' },
  { id: 67, pol: 'twardy', jap: 'katai', kana: 'かたい' },
  { id: 68, pol: 'ciężki', jap: 'omoi', kana: 'おもい' },
  { id: 69, pol: 'dziwny', jap: 'hen-na', kana: 'へんな' },
  { id: 70, pol: 'lekki', jap: 'karui', kana: 'かるい' },
  { id: 71, pol: 'skomplikowany', jap: 'fukuzatsu-na', kana: 'ふくざつな' },
  { id: 72, pol: 'zimny (np. dzień)', jap: 'samui', kana: 'さむい' },
  { id: 73, pol: 'zadowolony', jap: 'ureshii', kana: 'うれしい' },
  { id: 74, pol: 'daleki', jap: 'tooi', kana: 'とおい' },
  { id: 75, pol: 'chłodny', jap: 'suzushii', kana: 'すずしい' },
  { id: 76, pol: '~około', jap: 'goro', kana: 'ごろ' },
  { id: 77, pol: 'dobry (w czymś)', jap: 'jouzu-na', kana: 'じょうずな' },
  { id: 78, pol: 'znienawidzony', jap: 'kirai-na', kana: 'きらいな' },
  { id: 79, pol: 'młody', jap: 'wakai', kana: 'わかい' },
  { id: 80, pol: 'miły', jap: 'yasashii', kana: 'やさしい' },
  { id: 81, pol: 'miękki', jap: 'yowarakai', kana: 'やわらかい' },
  { id: 82, pol: 'zły (w czymś)', jap: 'heta-na', kana: 'へたな' },
  { id: 83, pol: 'świeży', jap: 'shinsen-na', kana: 'しんせんな' },
  { id: 84, pol: 'smutny', jap: 'kanashii', kana: 'かなしい' },
  { id: 85, pol: 'japońska jednostka podziału administracyjnego', jap: 'choume', kana: 'ちょうめ' },
  { id: 86, pol: 'ciastka, herbatniki', jap: 'okashi', kana: 'おかし' },
  { id: 87, pol: 'późny, powolny', jap: 'osoi', kana: 'おそい' },
  { id: 88, pol: 'licealista', jap: 'koukousei', kana: 'こうこうせい' },
  { id: 89, pol: 'wolny od pracy', jap: 'hima-na', kana: 'ひまな' },
  { id: 90, pol: 'nauczyciel', jap: 'kyoushi', kana: 'きょうし' },
  { id: 91, pol: 'manager', jap: 'maneejaa', kana: 'マネージャー' },
  { id: 92, pol: 'muzyka', jap: 'ongaku', kana: 'おんがく' },
  { id: 93, pol: 'biały', jap: 'shiroi', kana: 'しろい' },
  { id: 94, pol: 'czerwony', jap: 'akai', kana: 'あかい' },
  { id: 95, pol: 'szeroki', jap: 'hiroi', kana: 'ひろい' },
  { id: 96, pol: 'młodsza siostra (pańska)', jap: 'imoutosan', kana: 'いもうとさん' },
  { id: 97, pol: 'kawaler, kobieta niezamężna', jap: 'dokushin', kana: 'どくしん' },
  { id: 98, pol: 'dentysta', jap: 'haisha', kana: 'はいしゃ' },
  { id: 99, pol: 'dobrawdy? naprawdę?', jap: 'hontouni', kana: 'ほんとうに' },
  { id: 100, pol: 'ah tak? naprawdę?', jap: 'sou desu ka', kana: 'そうですか' },
  { id: 101, pol: 'łatwy (do zrozumienia)', jap: 'yasashii', kana: 'やさしい' },
  { id: 102, pol: 'zły', jap: 'warui', kana: 'わるい' },
  { id: 103, pol: 'nic', jap: 'nani-mo', kana: 'なにも' },
  { id: 104, pol: 'to miłe', jap: 'ureshii', kana: 'うれしい' },
  { id: 105, pol: 'dom', jap: 'ie', kana: 'いえ' },
  { id: 106, pol: 'aktor', jap: 'haiyuu', kana: 'はいゆう' },
  { id: 107, pol: 'piosenkarz', jap: 'kashu', kana: 'かしゅ' },
  { id: 108, pol: 'mąż (pani)', jap: 'goshujin', kana: 'ごしゅじん' },
  { id: 109, pol: 'samotny, smutny', jap: 'sabishii', kana: 'さびしい' },
  { id: 110, pol: 'prezent z podróży', jap: 'omiyage', kana: 'おみやげ' },
  { id: 111, pol: 'budynek', jap: 'tatemono', kana: 'たてもの' },
  { id: 112, pol: 'starszy brat (pański)', jap: 'oniisan', kana: 'おにいさん' },
  { id: 113, pol: 'rodzeństwo (moje)', jap: 'kyoudai', kana: 'きょうだい' },
  { id: 114, pol: 'rodzeństwo (pańskie)', jap: 'gokyoudai', kana: 'ごきょうだい' },
  { id: 115, pol: 'rodzina (moja)', jap: 'kazoku', kana: 'かぞく' },
  { id: 116, pol: 'rodzina (pańska)', jap: 'gokazoku', kana: 'ごかぞく' },
  { id: 117, pol: 'wyjątkowy', jap: 'mezurashii', kana: 'めずらしい' },
  { id: 118, pol: 'hałaśliwy', jap: 'nigiyaka-na', kana: 'にぎやかな' },
  { id: 119, pol: 'przystojny', jap: 'hansamu-na', kana: 'ハンサムな' },
  { id: 120, pol: 'ulubiony', jap: 'suki-na', kana: 'すきな' },
  { id: 121, pol: 'duży', jap: 'ooki-na', kana: 'おおきな' },
  { id: 122, pol: 'cienki, szczupły', jap: 'hosoi', kana: 'ほそい' },
  { id: 123, pol: 'student', jap: 'gakusei', kana: 'がくせい' },
  { id: 124, pol: 'groźny', jap: 'kowai', kana: 'こわい' },
  { id: 125, pol: 'nie ma za co', jap: 'dou itashimashite', kana: 'どういたしまして' },
  { id: 126, pol: 'zimny (w dotyku)', jap: 'tsumetai', kana: 'つめたい' },
  { id: 127, pol: 'to wspaniale, świetnie', jap: 'ii desu ne', kana: 'いいですね' },
  { id: 128, pol: 'turkusowy', jap: 'aoi', kana: 'あおい' },
  { id: 129, pol: 'pracownik firmy', jap: 'kaishain', kana: 'かいしゃいん' },
  { id: 130, pol: 'bezpieczny', jap: 'anzen-na', kana: 'あんぜんな' },
  { id: 131, pol: 'mama (pańska)', jap: 'okaasan', kana: 'おかあさん' },
  { id: 132, pol: 'syn (pański)', jap: 'musukosan', kana: 'むすこさん' },
  { id: 133, pol: 'syn (mój)', jap: 'musuko', kana: 'むすこ' },
  { id: 134, pol: 'dziennikarz', jap: 'kisha', kana: 'きしゃ' },
  { id: 135, pol: 'nowy', jap: 'atarashii', kana: 'あたらしい' },
  { id: 136, pol: 'supermarket', jap: 'suupa', kana: 'スーパー' },
  { id: 137, pol: 'gorący', jap: 'atsui', kana: 'あつい' },
  { id: 138, pol: 'tata (pański)', jap: 'otousan', kana: 'おとうさん' },
  { id: 139, pol: 'firma', jap: 'kaisha', kana: 'かいしゃ' },
  { id: 140, pol: 'niesmaczny', jap: 'mazui', kana: 'まずい' },
  { id: 141, pol: 'niebezpieczny', jap: 'abunai', kana: 'あぶない' },
  { id: 142, pol: 'łatwy (proste do zrobienia)', jap: 'kantan-na', kana: 'かんたんな' },
  { id: 143, pol: 'dokładnie, punkt', jap: 'choudo', kana: 'ちょうど' },
  { id: 144, pol: 'wąski', jap: 'semai', kana: 'せまい' },
  { id: 145, pol: 'dziecko (pańskie)', jap: 'okosan', kana: 'おこさん' },
  { id: 146, pol: 'ile kosztuje?', jap: 'ikura', kana: 'いくら' },
  { id: 147, pol: 'połowa', jap: 'han', kana: 'はん' },
  { id: 148, pol: 'wieczór', jap: 'yoru', kana: 'よる' },
  { id: 149, pol: 'południe', jap: 'hiru', kana: 'ひる' },
  { id: 150, pol: 'rano', jap: 'asa', kana: 'あさ' },
  { id: 151, pol: 'przed południem', jap: 'gozen', kana: 'ごぜん' },
  { id: 152, pol: 'po południu', jap: 'gogo', kana: 'ごご' },
  { id: 153, pol: 'teraz', jap: 'ima', kana: 'いま' },
  { id: 154, pol: 'kierowca', jap: 'untenshu', kana: 'うんてんしゅ' },
  { id: 155, pol: 'nauczyciel (mistrz, doktor)', jap: 'sensei', kana: 'せんせい' },
  { id: 156, pol: 'lekarz', jap: 'isha', kana: 'いしゃ' },
  { id: 157, pol: 'pielęgniarka', jap: 'kangofu, kangoshi', kana: 'かんごふ, かんごし' },
  { id: 158, pol: 'kolega, koleżanka', jap: 'tomodachi', kana: 'ともだち' },
  { id: 159, pol: 'kolega z pracy', jap: 'doryou', kana: 'どうりょう' },
  { id: 160, pol: 'stypendysta', jap: 'ryuugakusei', kana: 'りゅうがくせい' },
  { id: 161, pol: 'kraj', jap: 'kuni', kana: 'くに' },
  { id: 162, pol: 'matematyka', jap: 'suugaku', kana: 'すうがく' },
  { id: 163, pol: 'podstawówka', jap: 'shougakkou', kana: 'しょうがっこう' },
  { id: 164, pol: 'gimnazjum', jap: 'chuugakkou', kana: 'ちゅうがっこう' },
  { id: 165, pol: 'studia', jap: 'daigaku', kana: 'だいがく' },
  { id: 166, pol: 'młodsza siostra (moja)', jap: 'imooto', kana: 'いもうと' },
  { id: 167, pol: 'tani', jap: 'yasui', kana: 'やすい' },
  { id: 168, pol: 'rodzice (pańscy)', jap: 'goryoushin', kana: 'ごりょうしん' },
  { id: 169, pol: 'rodzice (moi)', jap: 'ryoushin', kana: 'りょうしん' },
  { id: 170, pol: 'sklep', jap: 'mise', kana: 'みせ' },
  { id: 171, pol: 'nudny', jap: 'tsumaranai', kana: 'つまらない' },
  { id: 172, pol: 'mały', jap: 'chiisa-na', kana: 'ちいさな' },
  { id: 173, pol: 'żółty', jap: 'kiiroi', kana: 'きいろい' },
  { id: 174, pol: 'małżeństwo, ślub', jap: 'kekkon', kana: 'けっこん' },
  { id: 175, pol: 'mama (moja)', jap: 'haha', kana: 'はは' },
  { id: 176, pol: 'tata (mój)', jap: 'chichi', kana: 'ちち' },
  { id: 177, pol: 'starsza siostra (czyjaś)', jap: 'oneesan', kana: 'おねえさん' },
  { id: 178, pol: 'starsza siostra (moja)', jap: 'ane', kana: 'あね' },
  { id: 179, pol: 'młodszy brat (pański)', jap: 'otoutosan', kana: 'おとうとさん' },
  { id: 180, pol: 'młodszy brat (mój)', jap: 'otouto', kana: 'おとうと' },
  { id: 181, pol: 'restauracja', jap: 'restoran', kana: 'レストラン' },
  { id: 182, pol: 'hotel', jap: 'hoteru', kana: 'ホテル' },
  { id: 183, pol: 'zabawny', jap: 'tanoshii', kana: 'たのしい' },
  { id: 184, pol: 'dom, rodzina', jap: 'uchi', kana: 'うち' },
  { id: 185, pol: 'mały', jap: 'chiisai', kana: 'ちいさい' },
  { id: 186, pol: 'duży', jap: 'ookii', kana: 'おおきい' },
  { id: 187, pol: 'przyjaciel, przyjaciółka', jap: 'yuujin', kana: 'ゆうじん' },
  { id: 188, pol: 'znajomy, znajoma', jap: 'shiriai', kana: 'しりあい' },
  { id: 189, pol: 'muzeum', jap: 'hakubutsukan', kana: 'はくぶつかん' },
  { id: 190, pol: 'smaczny', jap: 'oishii', kana: 'おいしい' },
  { id: 191, pol: 'starszy brat (mój)', jap: 'ani', kana: 'あに' },
  { id: 192, pol: 'córka (pańska)', jap: 'musumesan', kana: 'むすめさん' },
  { id: 193, pol: 'córka (moja)', jap: 'musume', kana: 'むすめ' },
  { id: 194, pol: 'liceum', jap: 'koutougakkou', kana: 'こうとうがっこう' },
  { id: 195, pol: 'ciepły', jap: 'atatakai', kana: 'あたたかい' },
  { id: 196, pol: 'wczesny, szybki', jap: 'hayai', kana: 'はやい' },
  { id: 197, pol: 'statek, łódź, okręt', jap: 'fune', kana: 'ふね' },
  { id: 198, pol: 'alkohol', jap: 'arukouru', kana: 'アルコール' },
  { id: 199, pol: 'piwo', jap: 'biiru', kana: 'ビール' },
  { id: 200, pol: 'morze', jap: 'umi', kana: 'うみ' },
  { id: 201, pol: 'pchać, naciskać', jap: 'osu', kana: 'おす' },
  { id: 202, pol: 'umierać', jap: 'shinu', kana: 'しぬ' },
  { id: 203, pol: 'jeść', jap: 'taberu', kana: 'たべる' },
  { id: 204, pol: 'park, ogród', jap: 'kouen', kana: 'こうえん' },
  { id: 205, pol: 'pić', jap: 'nomu', kana: 'のむ' },
  { id: 206, pol: 'toaleta', jap: 'toire', kana: 'トイレ' },
  { id: 207, pol: 'pociąg, tramwaj', jap: 'densha', kana: 'でんしゃ' },
  { id: 208, pol: 'biec, biegać', jap: 'hashiru', kana: 'はしる' },
  { id: 209, pol: 'wracać', jap: 'kaeru', kana: 'かえる' },
  { id: 210, pol: 'być (rzeczy nieożywione)', jap: 'aru', kana: 'ある' },
  { id: 211, pol: 'być (ludzie, zwierzęta)', jap: 'iru', kana: 'いる' },
  { id: 212, pol: 'robić', jap: 'suru', kana: 'する' },
  { id: 213, pol: 'rozumieć, wiedzieć', jap: 'wakaru', kana: 'わかる' },
  { id: 214, pol: 'znak, litera, słowo na...', jap: 'ji', kana: 'じ' },
  { id: 215, pol: 'pędzel', jap: 'fude', kana: 'ふで' },
  { id: 216, pol: 'gra', jap: 'gemu', kana: 'ゲーム' },
  { id: 217, pol: 'mniej więcej, około', jap: 'gurai', kana: 'ぐらい' },
  { id: 218, pol: 'tył, za czymś (ukryte, niewidoczne)', jap: 'ura', kana: 'うら' },
  { id: 219, pol: 'pieszo', jap: 'aruite', kana: 'あるいて' },
  { id: 220, pol: 'tylko trochę', jap: 'sukoshi dake', kana: 'すこしだけ' },
  { id: 221, pol: 'świątynia buddyjska', jap: 'otera', kana: 'おてら' },
  { id: 222, pol: 'posterunek policji', jap: 'kouban', kana: 'こうばん' },
  { id: 223, pol: 'biurowiec, wieżowiec', jap: 'biru', kana: 'ビル' },
  { id: 224, pol: 'kino', jap: 'eigakan', kana: 'えいがかん' },
  { id: 225, pol: 'restauracja', jap: 'restoran', kana: 'レストラン' },
  { id: 226, pol: 'wyjście', jap: 'deguchi', kana: 'でぐち' },
  { id: 227, pol: 'wejście, brama', jap: 'iriguchi', kana: 'いりぐち' },
  { id: 228, pol: 'centrum, dokładnie w środku', jap: 'mannaka', kana: 'まんなか' },
  { id: 229, pol: 'południe (kierunek)', jap: 'minami', kana: 'みなみ' },
  { id: 230, pol: 'dworzec kolejowy', jap: 'eki', kana: 'えき' },
  { id: 231, pol: 'wschód (kierunek)', jap: 'higashi', kana: 'ひがし' },
  { id: 232, pol: 'podróż, wycieczka', jap: 'ryokou', kana: 'りょこう' },
  { id: 233, pol: 'wszystkiego najlepszego! gratulacje!', jap: 'omedetou gozaimasu', kana: 'おめでとうございます' },
  { id: 234, pol: 'urlop, dzień wolny, wakacje', jap: 'kyuujitsu', kana: 'きゅうじつ' },
  { id: 235, pol: 'jak? dla czego? po co?', jap: 'doushite', kana: 'どうして' },
  { id: 236, pol: 'zagranica', jap: 'kaigai', kana: 'かいがい' },
  { id: 237, pol: 'powrót, wracanie', jap: 'kaeri', kana: 'かえり' },
  { id: 238, pol: 'Europa', jap: 'Yooroppa', kana: 'ヨーロッパ' },
  { id: 239, pol: 'wyjazd, wylot', jap: 'shuppatsu', kana: 'しゅっぱつ' },
  { id: 240, pol: 'data urodzenia', jap: 'seinen gappi', kana: 'せいねんがっぴ' },
  { id: 241, pol: 'urodziny', jap: 'tanjoubi', kana: 'たんじょうび' },
  { id: 242, pol: 'pomiędzy, wśród, odstęp', jap: 'aida', kana: 'あいだ' },
  { id: 243, pol: 'kiedy', jap: 'itsu', kana: 'いつ' },
  { id: 244, pol: 'jaki miesiąc', jap: 'nangatsu', kana: 'なんがつ' },
  { id: 245, pol: 'jaki dzień tygodnia', jap: 'nanyoubi', kana: 'なんようび' },
  { id: 246, pol: 'tylko', jap: 'dake', kana: 'だけ' },
  { id: 247, pol: 'godzina (czas trwania)', jap: 'jikan', kana: 'じかん' },
  { id: 248, pol: 'środek', jap: 'naka', kana: 'なか' },
  { id: 249, pol: 'koniecznie, obowiązkowo', jap: 'kanarazu', kana: 'かならず' },
  { id: 250, pol: 'zachód (kierunek)', jap: 'nishi', kana: 'にし' },
  { id: 251, pol: 'pobliże, blisko, obok, sąsiedztwo', jap: 'soba', kana: 'そば' },
  { id: 252, pol: 'prawo, prawa strona', jap: 'migi', kana: 'みぎ' },
  { id: 253, pol: 'powyżej, ponad, nad', jap: 'ue', kana: 'うえ' },
  { id: 254, pol: 'blisko', jap: 'chikaku', kana: 'ちかく' },
  { id: 255, pol: 'na zewnątrz, na dworze', jap: 'soto', kana: 'そと' },
  { id: 256, pol: 'przeciwna strona', jap: 'mukou', kana: 'むこう' },
  { id: 257, pol: 'postój taxi', jap: 'takushii noriba', kana: 'タクシーのりば' },
  { id: 258, pol: 'toaleta (grzecznie)', jap: 'otearai', kana: 'おてあらい' },
  { id: 259, pol: 'świątynia shintoistyczna', jap: 'jinja', kana: 'じんじゃ' },
  { id: 260, pol: 'front, przód, przed (położenie fizyczne)', jap: 'mae', kana: 'まえ' },
  { id: 261, pol: 'przednia strona, front (aspekt publiczny i formalny)', jap: 'omote', kana: 'おもて' },
  { id: 262, pol: 'poniżej, spód, pod, dół (fizyczne położenie)', jap: 'shita', kana: 'した' },
  { id: 263, pol: 'taxi', jap: 'takushii', kana: 'タクシー' },
  { id: 264, pol: 'motor', jap: 'baiku', kana: 'バイク' },
  { id: 265, pol: 'metro', jap: 'chikatetsu', kana: 'ちかてつ' },
  { id: 266, pol: 'szpital', jap: 'byouin', kana: 'びょういん' },
  { id: 267, pol: 'bank', jap: 'ginkou', kana: 'ぎんこう' },
  { id: 268, pol: 'sklep', jap: 'mise', kana: 'みせ' },
  { id: 269, pol: 'dom handlowy', jap: 'depaato', kana: 'デパート' },
  { id: 270, pol: 'supermarket', jap: 'suupaa', kana: 'スーパーマーケット' },
  { id: 271, pol: 'autobus', jap: 'basu', kana: 'バス' },
  { id: 272, pol: 'japoński pociąg ekspresowy', jap: 'shinkansen', kana: 'しんかんせん' },
  { id: 273, pol: 'północ (kierunek)', jap: 'kita', kana: 'きた' },
  { id: 274, pol: 'mięso', jap: 'niku', kana: 'にく' },
  { id: 275, pol: 'palić papierosy', jap: 'tabako-o suu', kana: 'たばこをすう' },
  { id: 276, pol: 'niebo', jap: 'sora', kana: 'そら' },
  { id: 277, pol: 'rozbierać się, zdejmować', jap: 'nugu', kana: 'ぬぐ' },
  { id: 278, pol: 'słyszeć, słuchać', jap: 'kiku', kana: 'きく' },
  { id: 279, pol: 'ciąć, kroić, przeciąć', jap: 'kiru', kana: 'きる' },
  { id: 280, pol: 'czekać', jap: 'matsu', kana: 'まつ' },
  { id: 281, pol: 'spadać, upaść', jap: 'ochiru', kana: 'おちる' },
  { id: 282, pol: 'spotykać się, widzieć się', jap: 'au', kana: 'あう' },
  { id: 283, pol: 'tył, z tyłu, za czymś', jap: 'ushiro', kana: 'うしろ' },
  { id: 284, pol: 'stać, wstawać', jap: 'tatsu', kana: 'たつ' },
  { id: 285, pol: 'język, dialekt, słowo', jap: 'kotoba', kana: 'ことば' },
  { id: 286, pol: 'sprzątać', jap: 'souji suru', kana: 'そうじする' },
  { id: 287, pol: 'patrzeć, widzieć', jap: 'miru', kana: 'みる' },
  { id: 288, pol: 'latać, lecieć', jap: 'tobu', kana: 'とぶ' },
  { id: 289, pol: 'wstawać', jap: 'okiru', kana: 'おきる' },
  { id: 290, pol: 'spieszyć się', jap: 'isogu', kana: 'いそぐ' },
  { id: 291, pol: 'lewo, lewa strona', jap: 'hidari', kana: 'ひだり' },
  { id: 292, pol: 'czytać', jap: 'yomu', kana: 'よむ' },
  { id: 293, pol: 'dużo, sporo', jap: 'takusan', kana: 'たくさん' },
  { id: 294, pol: 'odpoczywać', jap: 'yasumu', kana: 'やすむ' },
  { id: 295, pol: 'spać, iść spać', jap: 'neru', kana: 'ねる' },
  { id: 296, pol: 'obok, w pobliżu (bliżej niż soba)', jap: 'tonari', kana: 'となり' },
  { id: 297, pol: 'biuro, sekretariat', jap: 'jimushitsu', kana: 'じむしつ' },
  { id: 298, pol: 'następny', jap: 'tsugi', kana: 'つぎ' },
  { id: 299, pol: 'zupa, sok, bulion', jap: 'shiru', kana: 'しる' },
  { id: 300, pol: 'picie, napój', jap: 'nomimono', kana: 'のみもの' },
  { id: 301, pol: 'miejsce siedzące', jap: 'seki', kana: 'せき' },
  { id: 302, pol: "pisać", jap: "kaku", kana: "かく" },
  { id: 303, pol: "uczyć się", jap: "benkyou suru", kana: "べんきょうする" },
  { id: 304, pol: "rachunek, rozliczenie, zapłata", jap: "kaikei", kana: "かいけい" },
  { id: 305, pol: "pracować (czynność)", jap: "hataraku", kana: "はたらく" },
  { id: 306, pol: "opłata (za rachunek), rozliczenie (rachunku)", jap: "kanjou", kana: "かんじょう" },
  { id: 307, pol: "rozkaz, polecenie, prośba, życzenie (uprzejmie)", jap: "gochuumon", kana: "ごちゅうもん" },
  { id: 308, pol: "iść, jechać (oddalać się)", jap: "iku", kana: "いく" },
  { id: 309, pol: "metoda płatności", jap: "oshiharai houhou", kana: "おしはらいほうほう" },
  { id: 310, pol: "przyjść, przyjechać, przybyć (zbliżać się)", jap: "kuru", kana: "くる" },
  { id: 311, pol: "wyjmować, wyciągać", jap: "dasu", kana: "だす" },
  { id: 312, pol: "co roku", jap: "maitoshi", kana: "まいとし" },
  { id: 313, pol: "miejsce dla palących", jap: "kitsuen seki", kana: "きつえんせき" },
  { id: 314, pol: "zdjęcie, fotografia", jap: "shashin", kana: "しゃしん" },
  { id: 315, pol: "ostry, pikantny", jap: "karai", kana: "からい" },
  { id: 316, pol: "jedzenie na wynos", jap: "teikuauto", kana: "テイクアウト" },
  { id: 317, pol: "dom", jap: "ie", kana: "いえ" },
  { id: 318, pol: "wakacje, urlop", jap: "yasumi", kana: "やすみ" },
  { id: 319, pol: "zawsze", jap: "itsumo", kana: "いつも" },
  { id: 320, pol: "często", jap: "yoku", kana: "よく" },
  { id: 321, pol: "za dwa lata", jap: "sarainen", kana: "さらいねん" },
  { id: 322, pol: "ten rok", jap: "kotoshi", kana: "ことし" },
  { id: 323, pol: "co miesiąc", jap: "maitsuki", kana: "まいつき" },
  { id: 324, pol: "w przyszłym roku", jap: "rainen", kana: "らいねん" },
  { id: 325, pol: "pub", jap: "pabu", kana: "パブ" },
  { id: 326, pol: "ponieważ", jap: "kara", kana: "から" },
  { id: 327, pol: "wczoraj", jap: "kinou", kana: "きのう" },
  { id: 328, pol: "wczoraj wieczorem", jap: "yuube", kana: "ゆうべ" },
  { id: 329, pol: "w zeszłym miesiącu", jap: "sengetsu", kana: "せんげつ" },
  { id: 330, pol: "dwa tygodnie temu", jap: "nishuukan mae", kana: "にしゅうかんまえ" },
  { id: 331, pol: "dziś rano", jap: "kesa", kana: "けさ" },
  { id: 332, pol: "zeszły tydzień", jap: "senshuu", kana: "せんしゅう" },
  { id: 333, pol: "w zeszłym roku", jap: "kyonen", kana: "きょねん" },
  { id: 334, pol: "pięć lat temu", jap: "gonen mae", kana: "ごねんまえ" },
  { id: 335, pol: "cesarz", jap: "tennou", kana: "てんのう" },
  { id: 336, pol: "męski zaimek pierwszej osoby", jap: "boku", kana: "ぼく" },
  { id: 337, pol: "męski zaimek pierwszej osoby (nieformalny, wulgarny)", jap: "ore", kana: "おれ" },
  { id: 338, pol: "rzucić palenie", jap: "tobako-o yameru", kana: "たばこをやめる" },
  { id: 339, pol: "spóźnić się", jap: "okureru", kana: "おくれる" },
  { id: 340, pol: "własny, osobisty", jap: "jibun-no", kana: "じぶんの" },
  { id: 341, pol: "używać, posługiwać się", jap: "tsukau", kana: "つかう" },
  { id: 342, pol: "włożyć, wkładać", jap: "ireru", kana: "いれる" },
  { id: 343, pol: "łamać, zgiąć, składać, skręcać", jap: "oru", kana: "おる" },
  { id: 344, pol: "znaczek pocztowy", jap: "kitte", kana: "きって" },
  { id: 345, pol: "pudełko, skrzynia, szkatułka", jap: "hako", kana: "はこ" },
  { id: 346, pol: "wszyscy razem", jap: "minna-de", kana: "みんなで" },
  { id: 347, pol: "brać, wziąć, zbierać", jap: "toru", kana: "とる" },
  { id: 348, pol: "różne, rozmaite", jap: "iroiro-na", kana: "いろいろな" },
  { id: 349, pol: "mniej więcej, około", jap: "daitai", kana: "だいたい" },
  { id: 350, pol: "praca, zajęcie (rzeczownik)", jap: "shigoto", kana: "しごと" },
  { id: 351, pol: "wołać", jap: "yobu", kana: "よぶ" },
  { id: 352, pol: "wiedzieć (fakt, informacja)", jap: "shiru", kana: "しる" },
  { id: 353, pol: "samolot", jap: "hikouki", kana: "ひこうき" },
  { id: 354, pol: "droga", jap: "michi", kana: "みち" },
  { id: 355, pol: "wychodzić, wyruszać, wyjechać", jap: "deru", kana: "でる" },
  { id: 356, pol: "zbyt, raczej nie, niewiele, resztka, pozostałość", jap: "amari", kana: "あまり" },
  { id: 357, pol: "razem", jap: "isshoni", kana: "いっしょに" },
  { id: 358, pol: "wejść, wchodzić do, wsiadać", jap: "hairu", kana: "はいる" },
  { id: 359, pol: "pieniądze, gotówka, waluta", jap: "genkin", kana: "げんきん" },
  { id: 360, pol: "mówić, powiedzieć", jap: "iu", kana: "いう" },
  { id: 361, pol: "zamawiać, złożyć zamówienie", jap: "chuumon suru", kana: "ちゅうもんする" },
  { id: 362, pol: "płacić", jap: "harau", kana: "はらう" },
  { id: 363, pol: "rekomendacja, polecenie", jap: "osusume", kana: "おすすめ" },
  { id: 364, pol: "przymierzanie ubrań", jap: "shichaku", kana: "しちゃく" },
  { id: 365, pol: "już, jeszcze, kolejny, ponownie", jap: "mou", kana: "もう" },
  { id: 366, pol: "co tydzień", jap: "maishuu", kana: "まいしゅう" },
  { id: 367, pol: "każdego wieczoru", jap: "maiban", kana: "まいばん" },
  { id: 368, pol: "każdego ranka", jap: "maiasa", kana: "まいあさ" },
  { id: 369, pol: "codziennie", jap: "mainichi", kana: "まいにち" },
  { id: 370, pol: "czasami", jap: "tokidoki", kana: "ときどき" },
  { id: 371, pol: "przyszły tydzień", jap: "raishuu", kana: "らいしゅう" },
  { id: 372, pol: "w tym tygodniu", jap: "konshuu", kana: "こんしゅう" },
  { id: 373, pol: "dziś wieczorem", jap: "konban", kana: "こんばんは" },
  { id: 374, pol: "jutro", jap: "ashita", kana: "あした" },
  { id: 375, pol: "pojutrze", jap: "asatte", kana: "あさって" },
  { id: 376, pol: "popojutrze", jap: "shiasatte", kana: "しあさって" },
  { id: 377, pol: "dziś, dzisiaj", jap: "kyou", kana: "きょう" },
  { id: 378, pol: "rezerwacja", jap: "yoyaku", kana: "よやく" },
  { id: 379, pol: "miejsce dla niepalących", jap: "kinen seki", kana: "きねんせき" },
  { id: 380, pol: "bagaż, paczka", jap: "nimotsu", kana: "にもつ" },
  { id: 381, pol: "cały czas", jap: "zutto", kana: "ずっと" },
  { id: 382, pol: "iść się napić", jap: "nomi-ni iku", kana: "のみ に いく" },
  { id: 383, pol: "spóźnić się", jap: "chikoku-suru", kana: "ちこくする" },
  { id: 384, pol: "być zwolnionym", jap: "kubi-ninaru", kana: "くびになる" },
  { id: 385, pol: "potrawa, kuchnia", jap: "ryouri", kana: "りょうり" },
  { id: 386, pol: "głowa", jap: "atama", kana: "あたま" },
  { id: 387, pol: "włosy", jap: "kami", kana: "かみ" },
  { id: 388, pol: "szyja", jap: "kubi", kana: "くび" },
  { id: 389, pol: "twarz", jap: "kao", kana: "かお" },
  { id: 390, pol: "język (w buzi)", jap: "shita", kana: "した" },
  { id: 391, pol: "nos", jap: "hana", kana: "はな" },
  { id: 392, pol: "gardło", jap: "nodo", kana: "のど" },
  { id: 393, pol: "ząb", jap: "ha", kana: "は" },
  { id: 394, pol: "oko", jap: "me", kana: "め" },
  { id: 395, pol: "klatka piersiowa", jap: "mune", kana: "むね" },
  { id: 396, pol: "ucho", jap: "mimi", kana: "みみ" },
  { id: 397, pol: "plecy", jap: "senaka", kana: "せなか" },
  { id: 398, pol: "usta", jap: "kuchi", kana: "くち" },
  { id: 399, pol: "biodra", jap: "koshi", kana: "こし" },
  { id: 400, pol: "jelita", jap: "chou", kana: "ちょう" },
  { id: 401, pol: "żołądek", jap: "i", kana: "い" },
  { id: 402, pol: "kolano", jap: "hiza", kana: "ひざ" },
  { id: 403, pol: "łokieć, ramię", jap: "hiji", kana: "ひじ" },
  { id: 404, pol: "wprawny, dobry (w czymś)", jap: "jouzu", kana: "じょうず" },
  { id: 405, pol: "niewprawny, słaby (w czymś)", jap: "heta", kana: "へた" },
  { id: 406, pol: "wprawny, dobry (w czymś)", jap: "tokui", kana: "とくい" },
  { id: 407, pol: "niewprawny, słaby, nie dający sobie rady (w czymś)", jap: "nigate", kana: "にがて" },
  { id: 408, pol: "piękny, czysty", jap: "kirei-na", kana: "きれいな" },
  { id: 409, pol: "niski", jap: "hikui", kana: "ひくい" },
  { id: 410, pol: "jasny", jap: "akarui", kana: "あかるい" },
  { id: 411, pol: "płytki", jap: "asai", kana: "あさい" },
  { id: 412, pol: "torba", jap: "fukuro", kana: "ふくろ" }
];
